[package]
name = "basic_circuit"
type = "bin"
authors = [""]
compiler_version = ">=0.34.0"

[dependencies]
noir_string_search = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_string_search" }
noir_base64_standard = { path = "../../../noir_base64_standard" }