/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PermissionStruct = { publicKey: BytesLike; signature: BytesLike };

export type PermissionStructOutput = [publicKey: string, signature: string] & {
  publicKey: string;
  signature: string;
};

export type InEuint256Struct = { data: BytesLike };

export type InEuint256StructOutput = [data: string] & { data: string };

export declare namespace Fischietto {
  export type EncryptedMessageStruct = {
    part1: BigNumberish;
    part2: BigNumberish;
    part3: BigNumberish;
    part4: BigNumberish;
  };

  export type EncryptedMessageStructOutput = [
    part1: bigint,
    part2: bigint,
    part3: bigint,
    part4: bigint
  ] & { part1: bigint; part2: bigint; part3: bigint; part4: bigint };
}

export interface FischiettoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eip712Domain"
      | "getMessage"
      | "owner"
      | "reportExists"
      | "reports"
      | "whistle"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BigNumberish, PermissionStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whistle",
    values: [
      BigNumberish,
      [InEuint256Struct, InEuint256Struct, InEuint256Struct, InEuint256Struct],
      BigNumberish,
      string,
      string,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whistle", data: BytesLike): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Fischietto extends BaseContract {
  connect(runner?: ContractRunner | null): Fischietto;
  waitForDeployment(): Promise<this>;

  interface: FischiettoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getMessage: TypedContractMethod<
    [id: BigNumberish, permission: PermissionStruct],
    [[string, string, string, string]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  reportExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  reports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        Fischietto.EncryptedMessageStructOutput,
        bigint,
        string,
        string,
        string
      ] & {
        eMessage: Fischietto.EncryptedMessageStructOutput;
        timestamp: bigint;
        company: string;
        proof: string;
        kid: string;
      }
    ],
    "view"
  >;

  whistle: TypedContractMethod<
    [
      _id: BigNumberish,
      _eMessage: [
        InEuint256Struct,
        InEuint256Struct,
        InEuint256Struct,
        InEuint256Struct
      ],
      _timestamp: BigNumberish,
      _company: string,
      _proof: string,
      _kid: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [id: BigNumberish, permission: PermissionStruct],
    [[string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        Fischietto.EncryptedMessageStructOutput,
        bigint,
        string,
        string,
        string
      ] & {
        eMessage: Fischietto.EncryptedMessageStructOutput;
        timestamp: bigint;
        company: string;
        proof: string;
        kid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whistle"
  ): TypedContractMethod<
    [
      _id: BigNumberish,
      _eMessage: [
        InEuint256Struct,
        InEuint256Struct,
        InEuint256Struct,
        InEuint256Struct
      ],
      _timestamp: BigNumberish,
      _company: string,
      _proof: string,
      _kid: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
  };
}
