/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FischiettoInterface extends Interface {
  getFunction(nameOrSignature: "reports" | "whistle"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whistle",
    values: [BigNumberish, string, BigNumberish, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whistle", data: BytesLike): Result;
}

export interface Fischietto extends BaseContract {
  connect(runner?: ContractRunner | null): Fischietto;
  waitForDeployment(): Promise<this>;

  interface: FischiettoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string] & {
        message: string;
        timestamp: bigint;
        company: string;
        proof: string;
        kid: string;
      }
    ],
    "view"
  >;

  whistle: TypedContractMethod<
    [
      _id: BigNumberish,
      _message: string,
      _timestamp: BigNumberish,
      _company: string,
      _proof: string,
      _kid: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string] & {
        message: string;
        timestamp: bigint;
        company: string;
        proof: string;
        kid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whistle"
  ): TypedContractMethod<
    [
      _id: BigNumberish,
      _message: string,
      _timestamp: BigNumberish,
      _company: string,
      _proof: string,
      _kid: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
